#+TITLE: Acksin STRUM
#+AUTHOR: Acksin
#+OPTIONS: html-postamble:nil body-only: t

#+begin_quote
With my supervision,
primordial nature
brings forth the moving
and the nonmoving.

-- Bhagavad Gita
#+end_quote

* Introduction

Acksin STRUM is the tool to diagnose Linux issues quickly. It gives
you a complete picture of the CPU, Memory, IO, Networking, Processes,
Kernel Limits, etc. of a system. STRUM was born out of the frustration
that diagnosing an issue was to go through a mental checklist and
dealing with fallible human memory (especially at 3am when the pager
goes off). We hope that this tool will help.

* Basic Usage
** Syntax

We will reference the different keys of the output with the following
syntax.

=.System.Attribute= refers to

#+begin_src json
{
  "System": {
    "Attribute": "foobar"
  }
}
#+end_src

=.Processes.0.PID= refers to the first item in the array Processes.

#+begin_src json
  {
      "Processes": [
          {
              "Exe": "systemd",
              "PID": 1,
              "Memory": {
                  "Swap": {
                      "Size": 0,
                      "Unit": "kb"
                  }
              },
              "IO": {
                  "Limits": {
                      "OpenFiles": 65536,
                      "FileSize": 0,
                      "CPUTime": -1
                  },
                  "FD": null
              }
          }
      ]
  }
#+end_src

** Getting Help

#+begin_src sh :results output example :exports both
./strum --help
#+end_src

** Basic Usage

#+begin_src sh :results output code json :exports both :noweb
./strum
#+end_src

** Information on a Process

#+begin_src sh :results output code json :exports both :noweb
./strum 1505
#+end_src

** Alternate Outputs

#+begin_src sh :results output code json :exports both :noweb
./strum --output=flat
#+end_src

* Diagnostics
** System
** Cloud
*** AWS
** Process
*** Memory
*** CPU
*** Networking
*** IO
*** Limits
