syntax = "proto3";

package strumgrpc;

service StrumService {
  rpc PutStats (PutStatsRequest) returns (PutStatsReply) {}
}

message PutStatsRequest {
  string apiKey = 1
  string strumVersion = 2;
  string data = 3;
}

// The response message containing the greetings
message PutStatsReply {
  string message = 1;
}
